### ISSUE TITLE
Проект не компилируется со стандартными настройками javac

### ISSUE THREAD

**Issue by johnrembo** [navaroe/JavaCatalog#1]
$ javac Command.java 
Command.java:17: error: unmappable character (0xC2) for encoding UTF-8
                                                System.out.println("� �������� " + catalog.countCatalogPages() + " �������");
...

$ javac -encoding cp1251 src/objects/Console.java 
src/objects/Console.java:13: error: cannot find symbol
                Command decoder = new Command();
                ^
  symbol:   class Command
  location: class Console
src/objects/Console.java:13: error: cannot find symbol
                Command decoder = new Command();
                                      ^
  symbol:   class Command
  location: class Console
2 errors

**Comment by navaroe** [comment]
Для компиляции кода необходимо выполнить команду в корневом каталоге проекта:
javac -cp bin src/objects/Console.java
Для выполнения программы:
java -cp bin objects.Console

**Comment by johnrembo** [comment]
JavaCatalog/TestProject$ javac -cp bin src/objects/Console.java
src/objects/Console.java:12: error: cannot find symbol
                Command decoder = new Command();
                ^
  symbol:   class Command
  location: class Console
src/objects/Console.java:12: error: cannot find symbol
                Command decoder = new Command();
                                      ^
  symbol:   class Command
  location: class Console
2 errors

Правильный порядок скорее всего был:

$ javac -d bin src/objects/*
$ cd bin/
$ java objects.Console

Так же нужен рабочий пример использования:

catalog add 1
Selected category does not exist
category create 1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at objects.Command.read(Command.java:120)
        at objects.Console.main(Console.java:16)

category create 1 1
Category 1 created
catalog add 1

Command incorrect

**Comment by navaroe** [comment]
Добавил сообщения для ручного добавления/удаления категорий и позиций
При использовании шаблона каталога из текстового файла Список комманд.txt, категория 3 Напитки будет содержать пустую позицию и не выводиться в обычном представлении каталога. Можно вручную добавить эту категорию в каталог через команду catalog add 3, или же добавить непустую позицию в категорию / увеличить количество позиции 
position increase 3 Лимонад 1 для автоматического добавления непустой категории в каталог
